### ISSUE TITLE
No items populate in ui-scroll if height is applied after page-load

### ISSUE THREAD

**Issue by mbursill** [angular-ui/ui-utils#298]
I seem to have run into a ui-scroll bug. The items never populate if the height is applied after the directive has compiled.

My app uses the ui-router, and I have a unique way of injecting styles for the various states. It's a combination of a styleManager service and a directive named "head".  My state decelerations contain a custom data object with a css property (the path to the style sheet). A hook on the "$stateChangeSuccess" event will add or remove styles from the styleManager, which causes the "head" directive to compile a link tag to the style sheet.

Unfortunately, the event "$stateChangeSuccess" only occurs after the state template (and therefore the contained ui-scroll directive) has been compiled.

I'm using the 1.0 branch of ui-utils.

I have a workaround, but it's ugly:

```html
<!--
Because the searchResults class is added to the page
via the styleManager, it gets applied AFTER the ui-scroll directive has compiled.
This causes the ui-scroll to have no height, and therefore no items are populated.
The ui-scroll directive should probably detect the height change when the style does 
get applied, but it doesn't seem to do that.
The fix (hack) is to set an inline style for height, then to have the class set height
to auto with an !important declaration to override the inline height. This will
allow the ui-scroll to populate its buffer with the first batch of items. If the new
height is > the height it takes to render the first batch of items, the ui-scroll
will be unable to load additional batches of items (no scroll bar). The fix for
is to ensure buffer-size is large enough to invoke the scroll-bar.
 -->
<ul ui-scroll-viewport class="searchResults" style="height: 50px;">
    <li ui-scroll="item in itemsDataSource" buffer-size="20" ng-class-odd="'oddRow'" ng-class-even="'evenRow'">
        <div class="searchResultsItem" ng-click="onItemSelected(item)">
            <span>{{item.value}}</span>
        </div>
    </li>
</ul>
```
```css
.searchResults {
    height: auto !important;
    position: absolute;
    border-radius: 4px;
    top: 76px;
    bottom: 44px;
    left: 0;
    right: 0;
    overflow: auto;
    list-style-type: none;
    padding: 0;
    margin: 0;
    font-size: 1.5em;
    background-color: #F3F3F3;
    color: black;
}
```
